### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by jadperr** [supercrafter333/theWarn#2]
add config, how long will it be banned (1, 2, 3 or 7 days) good job :D

**Comment by supercrafter333** [comment]
Thaks for your feature-repuest. I add it to my TODO-list. Thx

**Comment by supercrafter333** [comment]
I've done it! Look at the dev branche and check if it works! When it works please let me know it here, then i implement it in the main branche! Thanks for your feature-request!

**Comment by supercrafter333** [comment]
implemented in main branch now.
